//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<movies> movies { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<langs> langs { get; set; }
        public virtual DbSet<formats> formats { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<directors> directors { get; set; }
        public virtual DbSet<actors> actors { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<genres> genres { get; set; }
    }
}
