//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movies()
        {
            this.duration = 120;
            this.age = 13;
            this.total_count = 1;
            this.price = 10m;
            this.left_count = 1;
            this.plot = "Null";
            this.orders = new HashSet<orders>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<short> year { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<short> duration { get; set; }
        public Nullable<byte> age { get; set; }
        public Nullable<byte> total_count { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<byte> left_count { get; set; }
        public string plot { get; set; }
        public Nullable<int> lang_id { get; set; }
        public Nullable<int> actor_id { get; set; }
        public Nullable<int> director_id { get; set; }
        public Nullable<int> format_id { get; set; }
        public string poster_path { get; set; }
        public string trailer_path { get; set; }
        public Nullable<int> genre_id { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual langs langs { get; set; }
        public virtual formats formats { get; set; }
        public virtual directors directors { get; set; }
        public virtual actors actors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        public virtual genres genre { get; set; }
    }
}
