//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class directors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public directors()
        {}
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }

		public virtual movies movie { get; set; }
	}
}
