//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.database
{
    using System;
    using System.Collections.Generic;

    public partial class movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movies()
        {
            this.left_count=1;
			this.total_count = 1;
		}
        public int id { get; set; }
        public string name { get; set; }
        public Int16 year { get; set; }
        public Int16 duration { get; set; }
        public decimal price { get; set; }
        public string plot { get; set; }
        public byte age { get; set; }
		public byte left_count{ get; set; }
		public byte total_count { get; set; }
		public int lang_id { get; set; }
		public byte format_id { get; set; }
		public int director_id { get; set; }
		public int country_id { get; set; }
		public int actor_id { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<langs> langs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genres> genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<countries> countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<countries> directors { get; set; }
		public virtual ICollection<countries> formats { get; set; }
		public virtual ICollection<countries> actors { get; set; }
	}
}
