//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
	{
        public roles()
		{
			this.movie_id = new HashSet<movies>();
		}
		public int id { get; set; }
        public string name { get; set; }
        public virtual actors actor_id { get; set; }
		public virtual ICollection<movies> movie_id { get; set; }
	}
}
