//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class acts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acts()
        {
            this.is_director = false;
        }
    
        public int Id { get; set; }
        public Nullable<bool> is_director { get; set; }
    
        public virtual actors actor { get; set; }
        public virtual movies movie { get; set; }
    }
}
